### ISSUE TITLE
Error: Cannot spaw command 'ctest'

### ISSUE THREAD

**Issue by MathiasMagnus** [fredericbonnet/cmake-test-explorer#1]
I tried the extension, and it fails to initialize with the error in the title. I saw there is no place to set the path to the CTest executable, so I added it to the PATH so a vanilla CLI invocation can find it. However, this did not solve the problem.

I'm using a Windows 10 machine, added a user entry to the PATH, relog, test on a vanilla command line that ctest.exe is found, but the extension within the IDE still cannot launch it, even after wiping the entire .vscode folder.

My `cmakeExplorer.buildDir` setting is set to `${workspaceRoot}/.vscode/build`, because that's where CMake Tools is set to place its output. I've set `cmakeExplorer.logfile` to be the same, but then I got this error:
```
Couldn't write log file ${workspaceRoot}/.vscode/build: Error: ENOENT: no such file or directory, open 'C:\Kellekek\Microsoft\VisualStudio\Code\${workspaceRoot}\.vscode\build'
```
Is the extension handling paths correctly? Why is the VS Code install path precede an unexpanded JSON variable?

**Comment by fredericbonnet** [comment]
Thanks for testing my extension!

The extension doesn't support variable expansion in the settings (for now, PRs welcome!). Try removing the leading `${workspaceRoot}` and it should work.

**Comment by fredericbonnet** [comment]
BTW I plan to add CTest path auto-detection soon, using the `CMakeCache.txt` file in the build folder. That way you won't have to put the executable in your PATH anymore.

**Comment by fredericbonnet** [comment]
@MathiasMagnus the new release 0.8.0 now integrates with CMake Tools and adds variable extension in settings (see pull request #8).
