### ISSUE TITLE
Feature request: Add paths to the environment when executing tests

### ISSUE THREAD

**Issue by zrno** [fredericbonnet/cmake-test-explorer#10]
Would it be possible to add folder locations as extra locations where the test executables can search for libraries like dlls? The extension C++ TestMate has this feature available.

**Comment by fredericbonnet** [comment]
Not sure why you'd need such a feature. The extension uses CTest to run the test executables (except in debug mode), so if your tests work from the command line then they should work as well from the extension. If they need those extra paths then you have to pass them to CTest anyway through e.g. environment variables. Do you have an example use case to illustrate your need?

**Comment by zrno** [comment]
The tests don't work from the command line. In our case they depend on some third party dll-s. There are plenty of questions and examples on stackoverflow where people search for the best solution to this issue. 

https://cmake.org/pipermail/cmake/2011-May/044234.html
https://cmake.org/pipermail/cmake/2015-November/061978.html

One solution is to create CMAKE commands that copy all the needed dll-s into the same folder where the unit test executables are. Another solution is to change the PC environment variables. The extension I mentioned in the first post allows us to add additional environment variables inside the IDE instead of polluting the whole environment of the PC.

You mention that we could pass the extra paths to CTest. Can you explain how or point to the documentation for that?

**Comment by fredericbonnet** [comment]
If your test only requires changes to the PATH env variable, then the best solution is to add the needed paths through the ENVIRONMENT test property. For example:

https://stackoverflow.com/questions/48954920/trouble-setting-environment-variables-for-ctest-tests

See the following CMake man pages;

https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html#properties-on-tests
https://cmake.org/cmake/help/latest/prop_test/ENVIRONMENT.html
https://cmake.org/cmake/help/latest/command/set_tests_properties.html

This solution ensures that CTest will pass the correct environment variables to the underlying test command without having to pass them explicitly on the command line. As the extension simply calls CTest and not the test command itself, this should work from VS Code as well.

**Comment by zrno** [comment]
Great. Thanks. That worked. Although it needed a very dirty workaround for windows to replace semicolon when the environment variable PATH is expanded.
` string(REPLACE ";" "\\;" PATH_FOR_CTEST "$ENV{PATH};path/to/thirdPartydllFolder")
  set_tests_properties(${PROJECT_NAME} PROPERTIES ENVIRONMENT "PATH=${PATH_FOR_CTEST}")`
