### ISSUE TITLE
Test do not load in WIndows

### ISSUE THREAD

**Issue by anagno** [fredericbonnet/cmake-test-explorer#14]
Hello,

Thank you for this great plug-in! 

Using the same project (https://github.com/anagno/gama) everything is working perfectly under ubuntu. The tests appear under the Test View and I am able to run them. But under windows the tests do not appear in the Test View (and I could not find any errors).

Any ideas why this might be happening ? Do I need to install something extra? Any ideas how I can debug it?

KR,

Vasileios

**Comment by fredericbonnet** [comment]
Hi, and thanks for using my extension!

Can you run the following command from within your Windows build directory?

```sh
ctest --show-only=json-v1
```

**Comment by anagno** [comment]
Thanks you for the great plugin and for the input !

```
{
  "backtraceGraph" :
  {
    "commands" : [],
    "files" : [],
    "nodes" : []
  },
  "kind" : "ctestInfo",
  "tests" : [],
  "version" :
  {
    "major" : 1,
    "minor" : 0
  }
}
```

The normal execution of  `ctest --show-only` prints the tests:

```
C:\Users\anagn\bin\gama\Debug>ctest --show-only
Test project C:/Users/anagn/bin/gama/Debug
  Test   #1: acord2-a2g
  Test   #2: acord2-a2diff
  Test   #3: gama_g3_adjustement_demo-g3-01_envelope
  Test   #4: gama_g3_adjustement_demo-g3-01_gso
  Test   #5: gama_g3_adjustement_demo-g3-01_cholesky
  Test   #6: gama_g3_adjustement_demo-g3-01_svd

...
```

Probably a bug in the cmake itself ...  :( So I will take it upstream !

**Comment by fredericbonnet** [comment]
Very strange, both commands should give the same test list. I hope you'll find the source of the error.

**Comment by anagno** [comment]
After the very fast response from the Cmake devs (https://gitlab.kitware.com/cmake/cmake/-/issues/21078) the solution is to add the configuration in the load args of the project. 

The problem arises because I am using a multi-config generator (and probably I am the root cause, since I am forcing the build type, due to the fact my conan scripts do not play nice with multi-config setups) . My settings are
```
    "cmake.buildDirectory": "${userHome}/bin/gama/${buildType}",
    "cmake.configureSettings": {
        "CMAKE_EXPORT_COMPILE_COMMANDS": true,
        "DCMAKE_BUILD_TYPE":"${buildType}"
    },
    "cmakeExplorer.cmakeIntegration":true,
    "cmakeExplorer.buildDir":"${buildDirectory}",
    "cmakeExplorer.buildConfig":"${buildType}",
    "cmakeExplorer.debugConfig":"stopAtEntryDebug",
    "cmakeExplorer.parallelJobs":-1,
    ***"cmakeExplorer.extraCtestLoadArgs": "-C ${buildType}",***
    "cmakeExplorer.extraCtestRunArgs":"-j 6",
```

Maybe it is worth being mentioned in the docs ?
Are multi-config generators considered in the plugin ?

**Comment by fredericbonnet** [comment]
Thanks for the feedback. The CMake team is very reactive indeed! I will add some words about this kind of issues and troubleshooting in the next version.
