### ISSUE TITLE
My test window doesnt populate

### ISSUE THREAD

**Issue by Dredok** [fredericbonnet/cmake-test-explorer#15]
Hi, 

I can't see any of the tests in the test window. 

If I run the ctest --show-only and ctest --show-only=json-v1; both commands shows all the tests.

I haven't found any log so I can't provide more information.

BTW. I'm developing using a docker container (Remote - Containers extension).

**Comment by Dredok** [comment]
okey I think I found the issue, I have to disable the Cmake integration in order to see the tests.
I don't have the CMake Tools extension

**Comment by fredericbonnet** [comment]
Thanks for your feedback, I'll add a Troubleshooting section in the doc for the next version. I consider disabling this option by default to avoid such issues.

**Comment by fredericbonnet** [comment]
The new release 0.10.0 should fix the issue.
