### ISSUE TITLE
Test not run when using the WORKING_DIRECTORY property (add_test function)

### ISSUE THREAD

**Issue by BigSeb** [fredericbonnet/cmake-test-explorer#17]
Tests does not seems to run when they are configured in CMake with the WORKING_DIRECTORY property. This attribute was added to the add_test call in CMake.

example:
`add_test(
        NAME ${file}
        COMMAND ${file}
        WORKING_DIRECTORY   ${CMAKE_CURRENT_LIST_DIR}
    )`

The test is successfully detected in TestExplorer, it can be 'run', it will get a green mark automatically but the test has not really run. Even a test that normally fails are marked as successful.

When looking at the Output window it looks like ctest was not started from the proper directory (the working directory is not the same location as the test binary folder)

- with the WORKING_DIRECTORY property:

`Test project F:/Projets/git/Test/Template/Template`

That path corresponds to the WORKING_DIRECTORY variable

- without the WORKING_DIRECTORY property:

```
Test project F:/Projets/git/Test/build/Visual Studio Community 2019 Release - amd64/Debug/Template/Template
    Start 1: adl
1/1 Test #1: adl ..............................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.02 sec
```
The path specified is the binary location of the test application (same that will appears if ctest is run manually even with the WORKING_DIRECTORY attribute)

Running the test manually with ctest or with CMake Tools runs as expected.

**Comment by fredericbonnet** [comment]
Thanks for the feedback, I'll try to reproduce the problem and will come back shortly.

**Comment by fredericbonnet** [comment]
OK I've found the problem. Prior to version 0.4.0 the extension used to execute the test commands directly, and did so from within the test's `WORKING_DIRECTORY`. Starting at 0.4.0 it uses CTest to run the test (see #4), however it still executes the `ctest` command from within `WORKING_DIRECTORY` instead of the build dir as it should be. This will be fixed in the next version.

**Comment by fredericbonnet** [comment]
The new release 0.10.0 should fix the issue. Can you confirm that it works on your side?

**Comment by BigSeb** [comment]
I can confirm now that it is working as expected. Tests are now run and looks to be run from the proper working directory.

Merci!
