### ISSUE TITLE
WORKING_DIRECTORY of test not propagated when debugging a test

### ISSUE THREAD

**Issue by MathiasMagnus** [fredericbonnet/cmake-test-explorer#18]
When you launch a test for debugging from the Test Explorer side panel (with the little bug icon), it doesn't seem to respect the `WORKING_DIRECTORY` set for the test otherwise. It runs from there, but debugging doesn't. I have tests that rely on DLLs built by the project and when launched from other places, they don't even hit main but instacrash in the debugger.

**Comment by fredericbonnet** [comment]
I can't reproduce the issue. For me both run and debug modes execute the test in WORKING_DIRECTORY. Do you have some code to share?

**Comment by MathiasMagnus** [comment]
Neither can I. :) Apologies for the crying wolf. I created a minimal repro that should've failed but didn't. (My issue was both instacrash and later that the debugger failed to find debug symbols, even when it found the library.) If I can pinpoint the issue in the larger repo, I'll reopen the issue.
