### ISSUE TITLE
SyntaxError: Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by vitaliivitko** [fredericbonnet/cmake-test-explorer#2]
Hi, It's a great extension, but I couldn't get it to work with my workspace. When I activate Test Explorer tab it says: Error while loading tests - click to show. And when I click I can see in the Output:
SyntaxError: Unexpected token T in JSON at position 0

**Comment by fredericbonnet** [comment]
Hi! Thanks for using my extension.

The extension works as follows:

- it calls the `ctest --show-only=json-v1` command from the CMake build dir; this command returns the list of CMake tests in JSON format
- it then parses the result and returns the test list to the Test Explorer UI
- if anything fails, it aborts and reports the error to the Test Explorer UI

Here the error looks like the ctest command returns unexpected result in a format other than JSON. Can you execute the following command from within your CMake build dir and post the result here?

```sh
ctest --show-only=json-v1
```

**Comment by vitaliivitko** [comment]
Interesting, when I run ctest command the output always starts with "Test project" - that explains why the error messages says: "Unexpected token T"
$ ctest --show-only=json-v1
Test project /home/.../.build
...

My ctest version is 3.10.2, I am using Ubuntu 18.

**Comment by fredericbonnet** [comment]
Ok, that's the source of the problem. It seems that the JSON output format was introduced in version 3.14, on older versions it only uses the human-friendly output. Upgrading CTest should fix the issue. The next version of the extension will include a compatibility mode if possible, or a better error message if not.

**Comment by vitaliivitko** [comment]
Nice! I've manually upgraded cmake and the extension works fine, thanks! Looking forward to your updates and new features.
