### ISSUE TITLE
custom debug configuration program is not overriden

### ISSUE THREAD

**Issue by dvirtz** [fredericbonnet/cmake-test-explorer#22]
Hi. I'm trying to use a custom debug configuration using the [CodeLLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) debug adapter under MacOS. 
The debug configuration I'm using is
```json
{
      "type": "lldb",
      "request": "launch",
      "name": "Test Debug"
}
```
however when I try to debug a test I get the message `"program" property is required for launch`. If I add a `program` field to the configuration then it takes it as is and doesn't override it with the test program.

versions:
VSCode: 1.50.1
CodeLLDB: v1.6.0
CMake Test Explorer: v0.10.0

**Comment by fredericbonnet** [comment]
Hi, and thanks for using my extension! I've pushed the new version 0.10.1 that should fix the problem, can you confirm it works on your side?

**Comment by dvirtz** [comment]
working great, thanks!
