### ISSUE TITLE
Debugging a test doesn't relay the environment to the debugger

### ISSUE THREAD

**Issue by MathiasMagnus** [fredericbonnet/cmake-test-explorer#25]
I have test which is reading some environment variables but finds them unset. When running through CTest they're found, but not when debugging the target. I found that `getCmakeTestDebugConfiguration()` [only captures](https://github.com/fredericbonnet/cmake-test-explorer/blob/master/src/cmake-runner.ts#L248) the CTest property `WORKING_DIRECTORY` property, but not [`ENVIRONMENT`](https://cmake.org/cmake/help/latest/prop_test/ENVIRONMENT.html). `vscode.DebugConfiguration` ought to have an `env` field (as far as I could tell) which should be populated with the content of said property.

**Comment by fredericbonnet** [comment]
Thanks for your feedback. Release v0.13.0 should fix this issue.
