### ISSUE TITLE
Usage of env variables

### ISSUE THREAD

**Issue by alanlivio** [fredericbonnet/cmake-test-explorer#28]
The cmake extension may use powershell env access in its variables, ex:
   `"cmake.buildDirectory": "${workspaceFolder}/_build-${buildType}-${env:OS}"` 
which is resolved to _build-Windows_NT on windows.

However, the cmake-tesplorer do not do the same, ex:
   `"cmakeExplorer.buildDir" : "${workspaceFolder}/_build-${buildType}-${env:OS}"` 
which is resolved to _build-${env:OS}

**Comment by kostiushko-vlad** [comment]
I have the same issue

**Comment by fredericbonnet** [comment]
That's a good idea, it will be integrated in the next release!

**Comment by fredericbonnet** [comment]
The new version 0.14.0 adds support for this syntax. 

https://github.com/fredericbonnet/cmake-test-explorer/releases/tag/v0.14.0
