### ISSUE TITLE
No support for Ctest named configuration

### ISSUE THREAD

**Issue by ColinDuquesnoy** [fredericbonnet/cmake-test-explorer#3]
Hi,

Nice work on this extension! It works very good in most cases except when user uses the named configuration feature of CTest, see https://cmake.org/cmake/help/v3.0/command/add_test.html CONFIGURATIONS. 

It would be nice to be able to specify the named configuration to use (in our case we use All, Unit, Integration,... and the test explorer shows no tests).

**Comment by fredericbonnet** [comment]
Thanks! I've just released a new version 0.3.0 that introduces a `buildConfig` setting for this purpose. Feedback welcome!

**Comment by ColinDuquesnoy** [comment]
Tested and approved. Many thanks! ;-)

**Comment by fredericbonnet** [comment]
Cool, closing the issue ;)
