### ISSUE TITLE
 Tests fail to run when multiple configurations are available

### ISSUE THREAD

**Issue by AlexDev2020** [fredericbonnet/cmake-test-explorer#31]
In the log file I see the following line "Test not available without configuration.  (Missing "-C <config>"?)".  

If I add to settings "cmakeExplorer.extraCtestRunArgs": "-C ${buildType}", then the tests run successfully. I expected that cmake-test-explorer will install the used configuration itself from cmakeExplorer.buildConfig.

**Comment by fredericbonnet** [comment]
Congratulation, you found a bug! The extension did pass the configuration to `ctest` when loading tests but not when running the same tests.

Release 0.14.1 hopefully fixes this issue. Thanks for reporting!
