### ISSUE TITLE
configure PATH environment var for running tests

### ISSUE THREAD

**Issue by alanlivio** [fredericbonnet/cmake-test-explorer#33]
I have a cmake windows build which use msys2 libraries in  C:\tools\msys64\mingw64\bin.
The test-explorer fail to load such libraries when running tests.
When I extends system PATH, the test-explorer works.

I would like to avoid extends the system PATH.
Is it possible a configure PATH when running tests?

**Comment by bkarasm** [comment]
I have similar issue. I'm capable of defining environment variables for debugging (using `cmakeExplorer.debugConfig`) but can't find a way to do the same when running tests by pressing the run button in the Test Explorer.

**Comment by alanlivio** [comment]
Hi @bkarasm. It exactly the same for. I was able to use cmakeExplorer.debugConfig for debugging. But I was not able to configure PATH for Test Explorer.

**Comment by fredericbonnet** [comment]
The new version [0.15.0](https://github.com/fredericbonnet/cmake-test-explorer/releases/tag/v0.15.0) adds `cmakeExplorer.extraCtestEnvVars` to set extra environment variables when running CTest. 

Values support variable substitutions, so if you want to extend the system path you can set the `PATH` variable to e.g. `${env:PATH};C:\tools\msys64\mingw64\bin`
