### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by meghadriG** [fredericbonnet/cmake-test-explorer#34]
[fredericbonnet.cmake-test-adapter-unresponsive.cpuprofile.txt](https://github.com/fredericbonnet/cmake-test-explorer/files/6711068/fredericbonnet.cmake-test-adapter-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `cmake-test-adapter`
- Extension Version: `0.14.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.57.1`

[fredericbonnet.cmake-test-adapter-unresponsive.cpuprofile.txt](https://github.com/fredericbonnet/cmake-test-explorer/files/6711070/fredericbonnet.cmake-test-adapter-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by fredericbonnet** [comment]
Thank you for your feedback. I've loaded the provided CPU profile but couldn't find any source of slowdown in the extension code, however the system call `close` seems to take a very unusual share of the total CPU time (around 96%). It looks that the slowdown occurs during module loading within the VS Code extension host, and not during the extension init per se. Can you reproduce this phenomenon on other systems? Maybe that's an antivirus or disk issue.

**Comment by meghadriG** [comment]
Thanks for looking into this. Knowing your findings is useful. Antivirus
has been disabled. I think your findings confirms a suspicion I've had that
there is something odd with this particular client client-owned and
provided machine.

--
Meghadri
