### ISSUE TITLE
Environment variables defined in debugConfig are ignored

### ISSUE THREAD

**Issue by bkarasm** [fredericbonnet/cmake-test-explorer#35]
I have a test that reads environment variables. I define those variables in debug configuration in `launch.json`, e.g.:
```
{
    "name": "myDebugConfig",
    "type": "cppdbg",
    "request": "launch",
    # ...
    "environment": [
        { "key": "MY_KEY", "value": "MY_VALUE" },    
    ]
}
```
I configure `cmakeExplorer.debugConfig` to use `myDebugConfig` and yet my test doesn't see `MY_KEY` to be defined.

**Comment by MathiasMagnus** [comment]
Because the schema says otherwise, this is how you control the environment for eg:
```json
"environment": [
    {
        "name": "CUDA_VISIBLE_DEVICES",
        "value": "2"
    }
]
```

**Comment by bkarasm** [comment]
My bad. Thanks @MathiasMagnus !
