### ISSUE TITLE
more granular activation events

### ISSUE THREAD

**Issue by dvirtz** [fredericbonnet/cmake-test-explorer#38]
Currently this extension is always activated which then activates the cmake-tools extensions which for non-cmake projects produces an annoying warning message about not finding a `CMakeLists.txt` file

![image](https://user-images.githubusercontent.com/7661709/134873218-67b61c12-28a4-4695-8237-76115f761b5f.png)

I'd recommend activating on the existence on the existence of a `CMakeLists.txt` in the project (similar to [cmake-tools](https://github.com/microsoft/vscode-cmake-tools/blob/ab01f5057335b2ae27d6841dd3ead9ca5e3e68c4/package.json#L83))

```
  "activationEvents": [
    "workspaceContains:**/CMakeLists.txt",
  ]
```

**Comment by dvirtz** [comment]
any plans to cut out a release with this fix?

**Comment by fredericbonnet** [comment]
Sorry I've been overwhelmed with real life recently, but I plan on releasing a new version by the end of the week (maybe even tonight).

**Comment by fredericbonnet** [comment]
Version 0.14.2 is live. I initially planned a 0.15.0 with new features and some maintenance but I don't want to delay your fix any longer. Thanks again!
