### ISSUE TITLE
Add a "Go to test" button

### ISSUE THREAD

**Issue by joao-aguirre** [fredericbonnet/cmake-test-explorer#40]
It would be very useful to have a "Go to test" additional button (alongside "Debug this test" and "Run this test") on the test tree view, that will open the (main) test file, in a similar fashion as the Python test explorer.

Here are the current CMake Test Explorer options:

![cmake-test-explorer](https://user-images.githubusercontent.com/11059665/134938263-0dadcc15-c77f-430f-9ce7-e02cf9d15876.png)

Here are the options from the Python Test Explorer:

![python-test-explorer](https://user-images.githubusercontent.com/11059665/134938281-71f3298c-279a-4187-af87-0a584aa7cbec.png)

Cheers.

**Comment by fredericbonnet** [comment]
The extension already supports this feature, however it requires explicit declaration as described here:

https://github.com/fredericbonnet/cmake-test-explorer#source-files

This is far from perfect, but alas there is no way for CTest to infer the right filename & line automatically from the test command alone.
