### ISSUE TITLE
Support for CodeLLDB launch configs

### ISSUE THREAD

**Issue by rjra100** [fredericbonnet/cmake-test-explorer#43]
We use CodeLLDB rather than CppTools for debugging. The launch.json configs are mostly the same, and up to version 0.14.2, this worked fine; we just point CMake Test Explorer's `cmakeExplorer.debugConfig` setting at an LLDB launch config and it'd work ok. As of 0.15 we're getting an error dialog `undefined is not iterable (cannot read property Symbol(Symbol.iterator))` when we attempt to debug a test from the test explorer.

I believe the reason is that CodeLLDB takes its environment settings in a different format from cpptools:
CppTools:
```json
    "environment": [
      {
        "name": "<varname>"
        "value": "<blah>"
      }
    ],
```
CodeLLDB:
```json
    "env": {
        "<varname>": "<blah>"
    }
```

If I add an empty environment list to the launch config it no longer produces errors, but that's going to be rather confusing! Could you support both formats?

For what it's worth, the same error occurs with a cpptools debug config with no environment list: that's less of a problem since it's created by default, but I think it should still work.

**Comment by fredericbonnet** [comment]
It looks like a bug caused by `cmakeExplorer.extraCtestEnvVars` handling in the new version. I only tested it on Windows with `cppvsdbg` and wrongly assumed that all debug configs used the same environment format, which unfortunately is not the case. I'm gonna fix that ASAP, sorry for the inconvenience!

**Comment by fredericbonnet** [comment]
Latest version should fix the issue, can you confirm it works on your side?

**Comment by rjra100** [comment]
Looks like it's working again as of v0.15.1. Thanks for the quick response!
