### ISSUE TITLE
The same tests are listed on all folders of multi-folder workspace

### ISSUE THREAD

**Issue by Maetveis** [fredericbonnet/cmake-test-explorer#46]
In a project with multiple folders the UI shows the tests for the currently selected workspace for all folders.

Given a multi folder workspace, both folders have a cmake build system with tests.
![image](https://user-images.githubusercontent.com/8176760/149300502-c331121c-0286-4073-8ab5-4c389dacb907.png)

With one of the folders selected:
![image](https://user-images.githubusercontent.com/8176760/149300585-6ae4b092-ce98-4c89-b026-634f0f47a9e1.png)
If selecting the other folder:
![image](https://user-images.githubusercontent.com/8176760/149300783-875f639b-9815-4b3b-b9cf-d4ee40811c07.png)

**Comment by fredericbonnet** [comment]
@Maetveis thanks for reporting! I can't reproduce the bug, can you share more context about your environment?

- settings for this extension
- do you have other extensions activated such as CMake Tools that could cause this problem?
- is there anything special about those CMake projects?

**Comment by Maetveis** [comment]
> @Maetveis thanks for reporting! I can't reproduce the bug, can you share more context about your environment?
> 
>     * settings for this extension

No explicit settings, default. ("testExplorer.useNativeTesting": true is set)

> 
>     * do you have other extensions activated such as CMake Tools that could cause this problem?

Cmake tools is installed along with twxs.cmake (cmake language support), and Test Adapeter UI (needed by Cmake test explorer)

> 
>     * is there anything special about those CMake projects?

Not that I'm aware of.

**Comment by fredericbonnet** [comment]
I've reproduced the bug with CMake Tools. Working on a fix.

**Comment by fredericbonnet** [comment]
Bad news, the bug is not fixable with the current version of CMake Tools. The cause of the bug is that the extension relies on a couple of CMake Tools commands to resolve the `${buildType}` and `${buildDirectory}` variables, and these commands only return the current workspace configuration and not the folder configuration. So both folders get the same build dirs, hence the bug.

I'm going to open an issue on their side so that they can provide these commands with multi-folder support.

**Comment by fredericbonnet** [comment]
Awesome! I totally missed that possibility when I studied their code. There doesn't seem to be any standard practice in argument passing to extension commands ([the API docs are pretty vague about it](https://code.visualstudio.com/api/references/vscode-api#commands.executeCommand)), so it's fortunate that they support it. It seems they introduced this possibility [a couple years ago](https://github.com/microsoft/vscode-cmake-tools/pull/958).

Your fix looks pretty straightforward so I'm gonna merge it and release a new version ASAP. Thanks again!

**Comment by fredericbonnet** [comment]
@Maetveis I've just published a new version with your fix, however I don't have the possibility to test it right now (I've broken my previous laptop and didn't have the time to rebuild the dev/test environments). Can you confirm that it works on your side?

**Comment by Maetveis** [comment]
> @Maetveis I've just published a new version with your fix, however I don't have the possibility to test it right now (I've broken my previous laptop and didn't have the time to rebuild the dev/test environments). Can you confirm that it works on your side?

Yep it works: the separate tests are now listed and running all runs both folders as expected. Should I try anything else?

BTW: thanks for the extension and the quick responses.

**Comment by fredericbonnet** [comment]
Maybe debugging individual tests, though I see no reason why it wouldn't work.

**Comment by Maetveis** [comment]
It works mostly gdb attaches, but the extension is still displaying as running tests when the debugger has stopped, as in the in-progress icon next to the testing tab is displayed and the cancel test run button is visible. New tests can be run just fine however. I don't know if this is a new issue, I did not try debugging tests before.

![image](https://user-images.githubusercontent.com/8176760/153777541-89545272-6146-4783-819e-248da2f3bc3a.png)

**Comment by fredericbonnet** [comment]
OK nothing too worrisome, I'll try to investigate the issue once I restore my environment. Thanks!
