### ISSUE TITLE
"environment is not iterable" when debugging test on macos

### ISSUE THREAD

**Issue by gracicot** [fredericbonnet/cmake-test-explorer#48]
When I'm trying to launch a test for bebugging in the CMake Test Explorer, I get an error saying "environment is not iterable"

<img width="297" alt="Screen Shot 2022-01-17 at 4 15 13 PM" src="https://user-images.githubusercontent.com/2906673/149826193-502bb98c-8612-44f6-9813-2ebd44685fb1.png">

It says to open the `launch.json`, whether or not this file exists.

If it does not exists, it ask me to create one, but it doesn't solve the problem.

**Comment by fredericbonnet** [comment]
@gracicot thanks! I tried to reproduce the bug on a macos machine (I only have Windows and Linux at home), I found the potential source of the problem but for some reason the debugger doesn't hit my breakpoints. That's just a local config issue, I can still debug it the old way though :)

**Comment by fredericbonnet** [comment]
Latest version 0.15.2 should fix the issue, can you confirm it works on your side?
