### ISSUE TITLE
Not respecting fixtures

### ISSUE THREAD

**Issue by mjvk** [fredericbonnet/cmake-test-explorer#5]
I am not sure which ctest command you use to run, but somehow it seems to skip any setup/cleanup fixtures. This results in tests failing. If I use ctest -L or -R it works fine?

**Comment by fredericbonnet** [comment]
Hi! At present the extension calls the discovered test commands directly, not through CTest (see #4). The next version will use CTest, so fixtures should work as expected.

**Comment by fredericbonnet** [comment]
The newest version should fix this issue, please tell me if it works on your side.
