### ISSUE TITLE
Can't run tests from gtest's TYPED_TEST with nested template type parameters

### ISSUE THREAD

**Issue by barometz** [fredericbonnet/cmake-test-explorer#51]
When I define a GoogleTest `TYPED_TEST` with a TypeParam that is a nested template specialization (such as `ClassTemplate<ClassTemplate<int>>`), the resulting test shows up correctly in the test explorer but I am unable to run it. When I click the "Run all tests" button, the status for that test does not change, nor when I run the individual test.
![image](https://user-images.githubusercontent.com/691020/155880458-d52ac15e-149f-47ed-8a65-519790134379.png)

A full project is at https://github.com/barometz/cmake-tx-repro, but the minimal repro (minus CMake config) is:

```c++
#include <gtest/gtest.h>

template <typename T> class ClassTemplate {};
template <typename T> using TypedFixture = testing::Test;
TYPED_TEST_SUITE(TypedFixture, testing::Types<ClassTemplate<ClassTemplate<int>>>);
TYPED_TEST(TypedFixture, Test) {}
```

My first hunch is it might be because of the space in the resulting test name (gtest's test name generation separates the closing `> >`, presumably for historical reasons). I'm going to see if I can find and resolve it this afternoon, but I figured I'd write the issue up first.

**Comment by fredericbonnet** [comment]
The new release [0.15.4](https://github.com/fredericbonnet/cmake-test-explorer/releases/tag/v0.15.4) includes your PR. Thanks again!
