### ISSUE TITLE
Disabled tests are marked as failed

### ISSUE THREAD

**Issue by rjra100** [fredericbonnet/cmake-test-explorer#56]
I've noticed that if we have tests which have been configured with the CTest DISABLED property, CTest correctly skips them but the tests show in the test explorer as failed (red X or equivalent icon). I imagine there's some sort of intermediate skipped/warning state that would probably be more appropriate for disabled tests, and failing that it would probably be preferable to have them marked as passed rather than failed.

I believe this applies to any test marked with `set_tests_properties(<name> PROPERTIES DISABLED True)` or equivalent, but in our case, the tests are defined in C++ GoogleTest, along the lines of `TEST(mytestcase, DISABLED_mytest) {...}`. They're then registered with `gtest_discover_tests(test_target)`. That produces a test registration CMake file along the lines of
```cmake
add_test([=[mytestcase.mytest]=] path/to/test_target.exe [==[--gtest_filter=mytestcase.DISABLED_mytest]==] --gtest_also_run_disabled_tests)
set_tests_properties( [=[--gtest_filter=mytestcase.DISABLED_mytest]=] PROPERTIES DISABLED True)
```

When run via ctest, that gives
```
Test project path/to/test_target.exe
    Start 1: mytestcase.mytest
1/1 Test #1: mytestcase.mytest ...***Not Run (Disabled)   0.00 sec
No tests were found!!!
```

But the test shows as failed in test explorer.

In case it's of interest, I notice that CLion has [exactly the same issue](https://youtrack.jetbrains.com/issue/CPP-26244/CTest-UI-CLion-counts-DISABLED-Google-Tests-as-failed)!

**Comment by fredericbonnet** [comment]
Thanks for reporting! The latest version [0.16.1](https://github.com/fredericbonnet/cmake-test-explorer/releases/tag/v0.16.1) fixes the issue.
