### ISSUE TITLE
empty tests list for after v0.14.1

### ISSUE THREAD

**Issue by alanlivio** [fredericbonnet/cmake-test-explorer#57]
Hi. I used cmake-test-explorer in the past successfully. But now I find an empty list when using it.
So, I tried rollback into multiple versions and the more recent version in which the extension work properly is v0.14.1. 
My stat is:
  code 1.73.0
  TestExplorer UI v2.21.1 
  TestAdater v0.1.6.

Any suggestion?

**Comment by fredericbonnet** [comment]
Hi, thanks for reporting! I can't reproduce the issue locally with the same versions as above, is there any error message displayed in the interface or the output pane?

**Comment by alanlivio** [comment]
Where exactly I can see error msgs? I tried this "Test Explorer" option at the tab "Output" tab but no msg.

![image](https://user-images.githubusercontent.com/604808/200165302-b447f4d1-95c1-40a6-bc97-6ff8ce0b0432.png)

I also use "cmakeExplorer.cmakeIntegration": true but nothing changes if disabled.
I also tried to disable and enable/disabled "testExplorer.useNativeTesting"

To be more precisely on my problem, please see the Testing tab:

in version >=0.14.2
![image](https://user-images.githubusercontent.com/604808/200165370-14e366c1-c1bc-4100-bd74-7c6eb8e54b07.png)

and in version 0.14.1 (expected)

![image](https://user-images.githubusercontent.com/604808/200165410-11f53f5c-2d3a-406f-bb94-f70eea81e34c.png)

**Comment by fredericbonnet** [comment]
The only change introduced by version 0.14.2 is this PR: https://github.com/fredericbonnet/cmake-test-explorer/pull/39

Basically it only activates the extension when a `CMakeFiles.txt` is present in the workspace. Can you check that it's the case?

**Comment by alanlivio** [comment]
Many thanks again @fredericbonnet. 

> it only activates the extension when a CMakeLists.txt is present in the workspace. Can you check that it's the case?

It is not the case. The CMakeLists.txs is at the root of my project https://github.com/telemidia/ginga

I tried clean VSCode caching but now even the testing button in the activities menu doesn't show up.


at >=0.14.2
![image](https://user-images.githubusercontent.com/604808/200298804-46ea4862-32f3-4e4b-aa72-ffc3166198af.png)


at <=0.14.1
![image](https://user-images.githubusercontent.com/604808/200298889-58f54bb7-6170-4ef9-a32e-1fd8017a246b.png)

**Comment by fredericbonnet** [comment]
Hmm that's strange, I've just cloned your project in a codespace and the test button is there, I can also display the log pane. Can you try in another environment ?

**Comment by alanlivio** [comment]
Many thanks @fredericbonnet 

> I've just cloned your project in a codespace and the test button is there

I discovered that the button is regarding the "testExplorer.useNativeTesting": true See the screecaptore below.

![Code_635](https://user-images.githubusercontent.com/604808/200559850-7a4a5fb1-ed41-40cc-8bad-04a384b408a6.gif)

> Can you try in another environment ?

I tried a WSL environment and had the same problem. See the below screenshots (without "testExplorer.useNativeTesting": false )
Do you have suggest I way to debug to find the error?


WSL env with 0.14.1

![Code_636](https://user-images.githubusercontent.com/604808/200566425-c2d6e159-ba87-4376-86eb-79904de82091.png)

WSL env with 0.14.2 

![image](https://user-images.githubusercontent.com/604808/200567726-3df7fac7-10ea-4662-861b-532b87b71939.png)

**Comment by alanlivio** [comment]
Hi again @fredericbonnet.  
To go further, I also tried this simple [cmake example ](https://github.com/gokhanettin/cmake-example) but I face the same problem. It works only at v0.14.1.
I also tried to enable `cmakeExplorer.logpanel` but did not log at "Output > Test Explorer".
Do you have another suggestion?

**Comment by fredericbonnet** [comment]
Hi, I managed to clone and compile your project on a Linux VM (sorry I don't have WSL), and the extension detects the tests just fine (after setting `cmakeExplorer.buildDir` to `${workspaceFolder}/build` since that's where the CMake build files are located). 

Setting `testExplorer.useNativeTesting` doesn't change anything besides the UI. Maybe there's a problem with your VS Code global settings that prevents the extension from activating properly, have you tried on another host machine? (not a VM with remote).

In the **Output** pane, under **Log (Extension Host)** you should see something like that:

```
2022-11-23 23:02:56.117 [info] ExtensionService#_doActivateExtension fredericbonnet.cmake-test-adapter, startup: true, activationEvent: 'workspaceContains:**/CMakeLists.txt'
```

**Comment by alanlivio** [comment]
>  managed to clone and compile your project on a Linux VM (sorry I don't have WSL), 
Sorry if I made confusion. My normal environment is windows11 with msys2. I only used the WSL because when you asked me to try another environment. I list below my attempts.

- FAIL: windows11, code 1.73.1, TestExplorer UI v2.21.1, TestAdater v0.1.6, camke-test-explorer >v0.14.1, msys2 tool chain (cmake, gcc, g++), testExplorer.useNativeTesting true/false
- FAIL: windows11, code 1.73.1, TestExplorer UI v2.21.1, TestAdater v0.1.6, camke-test-explorer >v0.14.1, WSL gcc tool chain (cmake, gcc, g++), testExplorer.useNativeTesting true/false

**Comment by fredericbonnet** [comment]
Hey, sorry for the delay. Can you try running the command **Developer: Show Running Extensions** and check whether the extension is listed there? You should also find **Test Explorer UI**. The **Developer: Open Extension Log Folder** is also useful to see all the log files produced by your extensions.

Also, maybe it's an issue with other extensions. Try disabling everything but this one and see if it changes anything.

In last resort you can try removing the activation event manually: go to the `%USERPROFILE%\.vscode\extensions` folder, find the extension folder `fredericbonnet.cmake-test-adapter-*`, edit the `package.json`, replace this line:

```json
	"activationEvents": [
		"workspaceContains:**/CMakeLists.txt"
	],
```

with: 

```json
	"activationEvents": [
		"*"
	],
```

Then reload the window (**Developer: Reload Window**). It should display the following message:

![image](https://user-images.githubusercontent.com/11368533/206308461-bd7ca501-3f74-4af3-b67e-47a41c65e509.png)

Click **Reload Window**, now the extension should be activated (check again with **Developer: Show Running Extensions**)

**Comment by alanlivio** [comment]
Many thanks for your time @fredericbonnet. It worked with that change at v0.16.3. I even double check by installing again, and it only works with that change.

**Comment by alanlivio** [comment]
Just to add that I still does not see the log at Output. I don't know if is also a problem.

![image](https://user-images.githubusercontent.com/604808/206495906-dc8e5f38-dc18-477b-bc98-8e5d65b984cf.png)

**Comment by fredericbonnet** [comment]
I have the same behavior, it seems that the native UI breaks test output support and that it only works with the Test Explorer UI. I plan to port the extension to the new test API eventually, hopefully there will be a way to fix that.

BTW the temporary fix will only work as long as you don't update the extension, I'll try to find a way to fix the activation in the next version.
