### ISSUE TITLE
Read cmakeExplorer.debugConfig from workspace file?

### ISSUE THREAD

**Issue by dslijepcevic** [fredericbonnet/cmake-test-explorer#59]
It seems that `cmakeExplorer.debugConfig` does not support launch configurations defined in workspace file. Could this be implemented?

**Comment by fredericbonnet** [comment]
Hi, thanks for reporting! I'll try to reproduce the problem ASAP.

**Comment by fredericbonnet** [comment]
I've reproduced the problem, indeed the extension doesn't load workspace file launch configurations, but unfortunately there is no way to do so as it's not supported by the VS Code extension API. I'll close the issue now but will add a proper note in the README file about this limitation.
