### ISSUE TITLE
How do I exclude some of the tests?

### ISSUE THREAD

**Issue by belousa** [fredericbonnet/cmake-test-explorer#6]
I have some tests that really should not be run every time. In fact, they should only be run on demand. In my CMake config I use -LE IntegrationTest  as extra switches for ctest. What can I do in TestExplorer?

**Comment by fredericbonnet** [comment]
I don't think this kind of feature is supported by TestExplorer UI. However I could add a new extension config setting for passing extra args to ctest at load time.

**Comment by fredericbonnet** [comment]
I've just released a new version 0.5.0 that adds the `extraCtestLoadArgs` and `extraCtestRunArgs` settings for passing extra args to CTest at load and run time respectively. You can use `extraCtestLoadArgs` to pass `-LE` and other options to filter your test list. Feedback welcome!

**Comment by woscostametaxa** [comment]
I am using 0.5.0 version; If I understand you correctly :
if I have a test with propertychange:
set_tests_properties(test_for_github PROPERTIES LABELS "format")

and in settings.json:
"cmakeExplorer.extraCtestLoadArgs": "-LE format"

it should not show test_for_github in my test list in the explorer view, correct?
Am I using it incorrectly or do I dont understand how it should work?

**Comment by fredericbonnet** [comment]
Yes it should work that way. If it doesn't then check that the command "ctest -N -LE format" works as expected from the shell.
