### ISSUE TITLE
CMake Test Explorer triggers CMake Tools to configure non CMake projects.

### ISSUE THREAD

**Issue by olafurw** [fredericbonnet/cmake-test-explorer#62]
Having CMake Test Explorer and CMake Tools installed and opening a non CMake project will trigger a configure CMake window to open.

![image](https://user-images.githubusercontent.com/103783/223364700-d700c019-0a75-4293-9189-d3791d90c3e6.png)

Initial bug report with CMake Tools but then figured out that it's CMake Test Explorer that's triggering this.

https://github.com/microsoft/vscode-cmake-tools/issues/3002

**Comment by fredericbonnet** [comment]
Thanks for reporting, I've reproduced the issue and will publish a fix today. This bug is likely caused by a fix I made for issue https://github.com/fredericbonnet/cmake-test-explorer/issues/57.

**Comment by fredericbonnet** [comment]
Latest release [v0.17.1 ](https://github.com/fredericbonnet/cmake-test-explorer/releases/tag/v0.17.1) fixes the issue.
