### ISSUE TITLE
Custom debug provider.

### ISSUE THREAD

**Issue by vladipus** [fredericbonnet/cmake-test-explorer#9]
Nice extension you got there!
Seems like there is a built-in support for cppdbg only. Would be great to have some other options (lldb), or even custom build launchers.

**Comment by fredericbonnet** [comment]
Thank you! I've just released version 0.7.0 with added support for custom debug config. Now you can define your own debug config in `launch.json` then provide its name in the extension settings. Feedback welcome ;)
